python test_time_pstarc.py --gpu_id 0 --opt_fe --K 5  --tta_bs 128 --tta_method pstarc --lamda 1.0 --dshift a2c --dataset officehome --tta_lr 5e-4
python test_time_pstarc.py --gpu_id 0 --opt_fe --K 5  --tta_bs 128 --tta_method pstarc --lamda 1.0 --dshift a2p --dataset officehome --tta_lr 5e-4
python test_time_pstarc.py --gpu_id 0 --opt_fe --K 5  --tta_bs 128 --tta_method pstarc --lamda 1.0 --dshift a2r --dataset officehome --tta_lr 5e-4
python test_time_pstarc.py --gpu_id 0 --opt_fe --K 5  --tta_bs 128 --tta_method pstarc --lamda 1.0 --dshift c2a --dataset officehome --tta_lr 5e-4
python test_time_pstarc.py --gpu_id 0 --opt_fe --K 5  --tta_bs 128 --tta_method pstarc --lamda 1.0 --dshift c2p --dataset officehome --tta_lr 5e-4
python test_time_pstarc.py --gpu_id 0 --opt_fe --K 5  --tta_bs 128 --tta_method pstarc --lamda 1.0 --dshift c2r --dataset officehome --tta_lr 5e-4
python test_time_pstarc.py --gpu_id 0 --opt_fe --K 5  --tta_bs 128 --tta_method pstarc --lamda 1.0 --dshift p2a --dataset officehome --tta_lr 5e-4
python test_time_pstarc.py --gpu_id 0 --opt_fe --K 5  --tta_bs 128 --tta_method pstarc --lamda 1.0 --dshift p2c --dataset officehome --tta_lr 5e-4
python test_time_pstarc.py --gpu_id 0 --opt_fe --K 5  --tta_bs 128 --tta_method pstarc --lamda 1.0 --dshift p2r --dataset officehome --tta_lr 5e-4
python test_time_pstarc.py --gpu_id 0 --opt_fe --K 5  --tta_bs 128 --tta_method pstarc --lamda 1.0 --dshift r2a --dataset officehome --tta_lr 5e-4
python test_time_pstarc.py --gpu_id 0 --opt_fe --K 5  --tta_bs 128 --tta_method pstarc --lamda 1.0 --dshift r2c --dataset officehome --tta_lr 5e-4
python test_time_pstarc.py --gpu_id 0 --opt_fe --K 5  --tta_bs 128 --tta_method pstarc --lamda 1.0 --dshift r2p --dataset officehome --tta_lr 5e-4